export { SnailTeam } from './SnailTeam'
export { TestEnemyTeam } from './TestEnemyTeam'
export { IronBloomTeam } from './IronBloomTeam'
export { HummingbirdAlliesTeam } from './HummingbirdAlliesTeam'
export { OrcHeroEliteTeam } from './OrcHeroEliteTeam'
export { TestSlug5HpTeam } from './TestSlug5HpTeam'
export { OrcWrestlerTeam } from './OrcWrestlerTeam'
