export { SnailTeam } from './SnailTeam'
export { TestEnemyTeam } from './TestEnemyTeam'
export { IronBloomTeam } from './IronBloomTeam'
export { HummingbirdScorpionTeam } from './HummingbirdScorpionTeam'
export { OrcHeroEliteTeam } from './OrcHeroEliteTeam'
export { TestSlug5HpTeam } from './TestSlug5HpTeam'
